[build]
  environment = { NODE_VERSION = "16.19.0" }
  command = "npm run build"
  publish = "./dist/"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "https://kaminrun-de.netlify.com/*"
  to = "https://kaminrun.de/:splat"
  status = 301
  force = true
